*** Variables ***
${URL APPLICATION}                 http://livraison3.testacademy.fr
${NAVIGATEUR}                      chrome
${UTILISATEUR VALIDE}              test
${MOT DE PASSE VALIDE}             test
${UTILISATEUR NON VALIDE}          nonvalide
${MOT DE PASSE NON VALIDE}         nonvalide
${TITRE TABLEAU DE BORD}           Tableau de bord - Livraison 3
${URL ANNONCE}                     http://livraison3.testacademy.fr/index.php/listing/beautiful-cove/
${NOM CONTACT}                     Jean
${EMAIL CONTACT}                   jean@test.fr
${TELEPHONE CONTACT}               0600000000
${MESSAGE CONTACT}                 Bonjour, je suis interesse.
${NOM INSCRIPTION}                 ALI_TEST
${EMAIL INSCRIPTION}               ali@test.fr
${MOT DE PASSE INSCRIPTION}        Ali123!
${CONFIRMATION INSCRIPTION}        Ali123!
