*** Variables ***
${API BASE URL}             https://mock-api-h0g7.onrender.com/
${API KEY}                  %{API_KEY}
${ID UTILISATEUR}          1
${PRENOM ATTENDU}          George
${NOM ATTENDU}             Bluth
${EMAIL ATTENDU}           george.bluth@api.testacademy.fr
${NOUVEAU PRENOM}          Api
${NOUVEAU NOM}             Test
${NOUVEL EMAIL}            api.test.1@testacademy.fr
${ID INEXISTANT}           999999
${EMAIL MISE A JOUR}       api.updated@testacademy.fr
